#!/usr/bin/env node

const autocannon = require('autocannon');
const fs = require('fs');
const path = require('path');

// Load test configuration
const config = require('./load-test-config.json');

// Create reports directory
const reportsDir = path.join(__dirname, 'reports', new Date().toISOString().split('T')[0]);
if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

// Generate JWT token for authenticated requests
async function generateJWT() {
  // In a real scenario, you would generate a proper JWT
  // For load testing, we'll use a mock token
  return 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzU5ZjZkZC0zNDc5LTRlNTgtOTNjMy1jMjllYTYyNDU0YzEiLCJlbWFpbCI6ImxvYWR0ZXN0QHN3aWZ0Z3VhcmQuY29tIiwiaWF0IjoxNzM3Mjg5NDYxLCJleHAiOjE3MzcyOTMwNjF9.mock_signature';
}

// Create load test for a specific endpoint
async function runLoadTest(endpointName, endpointConfig) {
  console.log(`\n🚀 Starting load test for ${endpointName}...`);
  
  const headers = {
    'Content-Type': 'application/json'
  };
  
  // Add authentication header if required
  if (endpointConfig.auth === 'user') {
    const token = await generateJWT();
    headers['Authorization'] = `Bearer ${token}`;
  }
  
  // Add user ID header for rate limiting
  if (endpointConfig.auth === 'user') {
    headers['x-user-id'] = config.testUser.id;
  }
  
  const autocannonConfig = {
    url: config.baseUrl + endpointConfig.path,
    method: endpointConfig.method,
    headers,
    body: JSON.stringify(endpointConfig.body),
    connections: 50,
    pipelining: 10,
    duration: 60,
    warmup: {
      duration: 10,
      connections: 10
    },
    requests: [
      {
        method: endpointConfig.method,
        path: endpointConfig.path,
        headers,
        body: JSON.stringify(endpointConfig.body)
      }
    ]
  };
  
  try {
    const result = await autocannon(autocannonConfig);
    
    // Generate report
    const report = generateReport(endpointName, result, endpointConfig);
    
    // Save report to file
    const reportFile = path.join(reportsDir, `${endpointName}.md`);
    fs.writeFileSync(reportFile, report);
    
    console.log(`✅ Load test completed for ${endpointName}`);
    console.log(`📊 Report saved to: ${reportFile}`);
    
    return result;
  } catch (error) {
    console.error(`❌ Load test failed for ${endpointName}:`, error.message);
    return null;
  }
}

// Generate markdown report
function generateReport(endpointName, result, endpointConfig) {
  const timestamp = new Date().toISOString();
  const rateLimit = endpointConfig.rateLimit;
  
  return `# Load Test Report: ${endpointName}

**Generated:** ${timestamp}
**Endpoint:** ${endpointConfig.method} ${endpointConfig.path}
**Rate Limit:** ${rateLimit.maxRequests} requests/${rateLimit.windowMinutes}min

## Performance Metrics

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| **Requests/sec** | ${result.requests.average.toFixed(2)} | > 10 | ${result.requests.average > 10 ? '✅' : '❌'} |
| **Latency p50** | ${result.latency.p50}ms | < 300ms | ${result.latency.p50 < 300 ? '✅' : '❌'} |
| **Latency p95** | ${result.latency.p95}ms | < 700ms | ${result.latency.p95 < 700 ? '✅' : '❌'} |
| **Latency p99** | ${result.latency.p99}ms | < 1000ms | ${result.latency.p99 < 1000 ? '✅' : '❌'} |
| **Error Rate** | ${(result.non2xx / result.requests.total * 100).toFixed(2)}% | < 1% | ${(result.non2xx / result.requests.total) < 0.01 ? '✅' : '❌'} |
| **Timeouts** | ${result.timeouts} | 0 | ${result.timeouts === 0 ? '✅' : '❌'} |

## Detailed Results

- **Total Requests:** ${result.requests.total}
- **Successful Requests:** ${result.requests.total - result.non2xx}
- **Failed Requests:** ${result.non2xx}
- **Duration:** ${result.duration}s
- **Throughput:** ${result.throughput.average.toFixed(2)} bytes/sec

## Latency Distribution

- **Min:** ${result.latency.min}ms
- **Max:** ${result.latency.max}ms
- **Mean:** ${result.latency.average.toFixed(2)}ms
- **Std Dev:** ${result.latency.stddev.toFixed(2)}ms

## Rate Limiting Analysis

- **Rate Limit Triggered:** ${result.non2xx > 0 ? 'Yes' : 'No'}
- **429 Responses:** ${result.non2xx} (${(result.non2xx / result.requests.total * 100).toFixed(2)}%)

## Recommendations

${generateRecommendations(result, endpointConfig)}

---
*Generated by SwiftGuard Load Testing Suite*
`;
}

// Generate recommendations based on results
function generateRecommendations(result, endpointConfig) {
  const recommendations = [];
  
  if (result.latency.p95 > 700) {
    recommendations.push('- **High p95 latency**: Consider adding database indexes or caching');
  }
  
  if (result.latency.p99 > 1000) {
    recommendations.push('- **High p99 latency**: Review query performance and add monitoring');
  }
  
  if ((result.non2xx / result.requests.total) > 0.01) {
    recommendations.push('- **High error rate**: Investigate error causes and improve error handling');
  }
  
  if (result.timeouts > 0) {
    recommendations.push('- **Timeouts detected**: Increase timeout values or optimize slow operations');
  }
  
  if (result.requests.average < 10) {
    recommendations.push('- **Low throughput**: Consider horizontal scaling or performance optimization');
  }
  
  if (recommendations.length === 0) {
    recommendations.push('- **Performance is within acceptable limits**');
  }
  
  return recommendations.join('\n');
}

// Run all load tests
async function runAllLoadTests() {
  console.log('🎯 SwiftGuard Load Testing Suite');
  console.log('================================');
  
  const results = {};
  
  for (const [endpointName, endpointConfig] of Object.entries(config.endpoints)) {
    const result = await runLoadTest(endpointName, endpointConfig);
    results[endpointName] = result;
    
    // Wait between tests to avoid overwhelming the system
    await new Promise(resolve => setTimeout(resolve, 5000));
  }
  
  // Generate summary report
  const summaryReport = generateSummaryReport(results);
  const summaryFile = path.join(reportsDir, 'summary.md');
  fs.writeFileSync(summaryFile, summaryReport);
  
  console.log(`\n📋 Summary report saved to: ${summaryFile}`);
  console.log('\n🎉 All load tests completed!');
}

// Generate summary report
function generateSummaryReport(results) {
  const timestamp = new Date().toISOString();
  
  let report = `# SwiftGuard Load Testing Summary

**Generated:** ${timestamp}

## Overall Results

| Endpoint | RPS | p95 Latency | Error Rate | Status |
|----------|-----|-------------|------------|--------|
`;
  
  let allPassed = true;
  
  for (const [endpointName, result] of Object.entries(results)) {
    if (!result) {
      report += `| ${endpointName} | ❌ FAILED | ❌ FAILED | ❌ FAILED | ❌ FAILED |\n`;
      allPassed = false;
      continue;
    }
    
    const rps = result.requests.average.toFixed(2);
    const p95 = result.latency.p95;
    const errorRate = (result.non2xx / result.requests.total * 100).toFixed(2);
    const status = (p95 < 700 && (result.non2xx / result.requests.total) < 0.01) ? '✅ PASS' : '❌ FAIL';
    
    if (status === '❌ FAIL') allPassed = false;
    
    report += `| ${endpointName} | ${rps} | ${p95}ms | ${errorRate}% | ${status} |\n`;
  }
  
  report += `\n## Overall Status: ${allPassed ? '✅ ALL TESTS PASSED' : '❌ SOME TESTS FAILED'}\n\n`;
  
  report += `## Recommendations\n\n`;
  
  if (allPassed) {
    report += `- All endpoints are performing within acceptable limits\n`;
    report += `- System is ready for production load\n`;
  } else {
    report += `- Review failed endpoints and implement optimizations\n`;
    report += `- Consider scaling infrastructure before production deployment\n`;
  }
  
  report += `\n---\n*Generated by SwiftGuard Load Testing Suite*\n`;
  
  return report;
}

// Run the load tests
if (require.main === module) {
  runAllLoadTests().catch(console.error);
}

module.exports = { runLoadTest, runAllLoadTests };

